apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deploy
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: gcr.io/amir-265013/node-app:master
        ports:
        - containerPort: 3000