apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-srv
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
  - port: 80
    targetPort: 3000
    #nodePort: 30036
    protocol: TCP